### ISSUE TITLE
Imported Region missing almost all Resources (except IAM, Tags, Cloudfront)

### ISSUE THREAD

**Issue by typeacyclist** [awslabs/workload-discovery-on-aws#204]
The main "Global" region has all resources discovered.  However, an imported Region (us-east-2) does not show any Resource Types other than IAM, Tags, Cloudfront.

Confirmed no 400 or 500 error from this post https://docs.aws.amazon.com/solutions/latest/aws-perspective/debugging-the-discovery-component.html

1. Login to https://d34uafff7qltwf.cloudfront.net/
2. Click Preferences > Filters
3. Select Account and select "show" Region that you want to diagram 
4. Click Resource Types tab
5. Only 1 page with IAM, Tags, Cloudfront are shown compared to 3 pages with all Resources from the primary 'global' install region

Screenshot top image is from additional imported region us-east-2, and the bottom is the primary region imported first.

![image](https://user-images.githubusercontent.com/55901253/132382887-7e69950a-a8bd-4f56-a752-1437d142887c.png)
![2021-09-07_10-52-44](https://user-images.githubusercontent.com/55901253/132382926-b7a7bf65-0097-4ce1-acad-73ca07f38ab0.jpg)

**Comment by thebutler12** [comment]
Hey,

Can you see the missing resources in the AWS Config console in the AWS Perspective deployment Region?

Cheers,

Matt

**Comment by typeacyclist** [comment]
Yes, in AWS Config there are (2729) Resources for my Ohio region us-east-2; and, (718) Resources for my N VA region us-east-1.
However, in Perspectives, there are (0) non-Global Resources showing. ☹


-Matt
Matt Gabrielson
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Zoom https://trendzact.zoom.us/my/matt.g.trendzact
Website https://trendzact.com/
Availability Calendar https://calendly.com/trendzact-mg1

**Comment by thebutler12** [comment]
Thanks for the info.

To confirm you have imported 3 Regions: ap-northeast-1, us-east-1, and us-east-2 with us-east-1 being the first one imported. Are you experiencing the same issue when selecting ap-northeast-1 Region?

**Comment by typeacyclist** [comment]
Yes, imported (3) but only (2) are active: us-east-1 and us-east-2; and only us-east-1 has non-global resources.


-Matt
Matt Gabrielson
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Zoom https://trendzact.zoom.us/my/matt.g.trendzact
Website https://trendzact.com/
Availability Calendar https://calendly.com/trendzact-mg1

**Comment by thebutler12** [comment]
If you set the filter toggles to "Show" resource from all your account and Regions. Can you see the resources in the left-hand side panel? 

A why to test this would be to expand "Types" under "Resources" and select a resource type that you know exists in both accounts/Regions.

**Comment by typeacyclist** [comment]
Yes, it shows (3) imported regions on the left, but no regional resources.   This has become too time-consuming and a waste of time.  Sorry but Perspectives isn’t ready as a paid product.


-Matt
Matt Gabrielson
Trendzact®
385-434-3251 (direct)
385-434-3250 (main)
Zoom https://trendzact.zoom.us/my/matt.g.trendzact
Website https://trendzact.com/
Availability Calendar https://calendly.com/trendzact-mg1

**Comment by thebutler12** [comment]
Sorry you think that. I have been trying to replicate this issue but have not been able to do so.

I know back and forth interactions in GitHub issues can be time consuming, but could you show us a screenshot of the full "Regions" tab in the "Filters" dialog so we can see the full set of filters applied. This will be helpful for our investigations. If you can also check in the UI under "Settings" --> "Imported regions" what the last scanned value is just so we know whether the discovery process is running at it's regular intervals.

We want to make sure we identify what is causing this issue and get a fix out if necessary.

Thanks.
