### ISSUE TITLE
GraphQLSchemaException No schema definition exists

### ISSUE THREAD

**Issue by ttlnd** [awslabs/workload-discovery-on-aws#208]
**Describe the bug**
{errors: [{errorType: "GraphQLSchemaException", message: "No schema definition exists."}]}

As seen in the screenshot

**To Reproduce**

1. New perspective stack
2. First login and change the PW
3. graphql error

**Expected behavior**
A working solution

**Screenshots**
![Skärmbild 2021-09-20 094552](https://user-images.githubusercontent.com/11815091/133970476-19899054-4204-43c6-ade1-b706b0f3407d.png)

**Comment by ctsimpouris** [comment]
I experience the same problem, and seems that various nested stacks failed to deploy.
![image](https://user-images.githubusercontent.com/42470074/145202504-c78bd743-4eab-428e-8454-37920c3ae116.png)

![image](https://user-images.githubusercontent.com/42470074/145202597-f07a9b65-e8bf-4145-8f3d-1537e771c597.png)
![image](https://user-images.githubusercontent.com/42470074/145202645-fbf0d97e-b42e-47df-8d82-fcbb2dab47de.png)
![image](https://user-images.githubusercontent.com/42470074/145202676-7f2ca888-1a05-4204-8551-839c67f76cc1.png)

If this is related to elastic IPs, I will try a different region and see how it goes.
