### ISSUE TITLE
DrawIO export fails with collapsed group

### ISSUE THREAD

**Issue by an-echo** [awslabs/workload-discovery-on-aws#219]
Export to DrawIO fails when a group is collapse. If I Show All, I can export again.

**To Reproduce**

1. Place the Perspective ElasticSearch resource on a new diagram
2. Go to Export/Drawio --> it exports the diagram as expected
3. right click on TAG resources and select Collapse All
3. Go to Export/Drawio -->  nothing happens (drawio diagram is not exported)

**Expected behavior**
Drawio diagram should be exported even with collapsed resources

**Browser (please complete the following information):**

- Firefox (MacOS)  94.01
- Chrome (MacOS) 95.0.4638.69

**Comment by thebutler12** [comment]
Hey, thanks for raising the bug. We will look into this.

**Comment by svozza** [comment]
This was fixed in v1.1.4.
