### ISSUE TITLE
ECS DB getting corrupted during region import post-step

### ISSUE THREAD

**Issue by eb-j** [awslabs/workload-discovery-on-aws#260]
I am currently encountering the exact same issue with a new Perspective installation as described in #183. While importing regions as a part of post-steps, I start getting the "We could not load resource configuration" message as described in #137, except I had about 6000 resources populated before the message started popping up (i.e. ZoomDiscoveryRole is working). To try and resolve this, I have been following the advice listed in #126 to "wipe down" the DB. Doing so makes the service usable again, but only until about 4000 resources are discovered and then it starts showing the "We could not load resource configuration" message again. I checked the errors in CloudWatch and they are the same as the ones listed in #183. FYI this is now my second attempt at an installation where this same issue has occurred.

**Describe the bug**
ECS DB getting corrupted during region import post-step

**To Reproduce**
New CloudFormation install (v.1.1.3) with all defaults except Config is already setup, region import post-step; attempting to import 30 external accounts with 4 regions each (i.e. 120 total regions)

**Expected behavior**
I get through importing about 20 of the accounts when the issue starts.

**Screenshots**
As mentioned, it is a combination of a number of bugs, but seems likely to be an issue with the ECS DB given #126 gets the service working again, but only temporarily. 

**Browser (please complete the following information):**

- Chrome
- Version 98.0.4758.102

**Additional context**

**Comment by eb-j** [comment]
Turning on filters helps to make the service usable, but the filters themselves are acting strange, i.e. when I turn a few off, others will turn themselves on...

**Comment by svozza** [comment]
The issue here is that the payload from lambda has exceeded the 6Mb limit, the reason the filters work is because they reduce the size of payload back below that limit. In the new version of Perspective (v2.0.0) that we have just start working on, we have introduced pagination that will fix this problem. Unfortunately, we are only in the early stages of development and I can't provide an expected release date at this moment in time.

**Comment by svozza** [comment]
This new version was [released](https://aws.amazon.com/solutions/implementations/workload-discovery-on-aws/) today, and the frontend now uses a paginated API to load resources.
