### ISSUE TITLE
support for AWS OpenSearch

### ISSUE THREAD

**Issue by christian-smith-near** [awslabs/workload-discovery-on-aws#297]
**Feature name**
OpenSearch integration

**Is your feature request related to a problem? Please describe.**
Currently we can't visualize any OS resources discovered regardless if Config picks them up or not

**Describe the feature you'd like to see implemented**
I'd like to be able to visualize OS domains

**Describe the value this feature will add to AWS Perspective**
This would expand the supported resources to include a heavily used product

**Comment by svozza** [comment]
Support for OpenSearch has been added to v2.0.0 that was released today.
