### ISSUE TITLE
ECS is not shown in Resources available

### ISSUE THREAD

**Issue by neldyan14** [awslabs/workload-discovery-on-aws#303]
If your issue relates to the _Discovery Process_, please first follow the steps described in the implementation guide [Debugging the Discovery Component](https://docs.aws.amazon.com/solutions/latest/aws-perspective/appendix-e-debugging-the-discovery-component.html)

---

**Describe the bug**
A description of what the bug is.
I cannot view / add the ECS resources .

**To Reproduce**

**Expected behavior**
A description of what you expected to happen.

**Screenshots**

**Browser (please complete the following information):**

- Name [e.g. chrome, firefox]

**Additional context**

**Comment by svozza** [comment]
There was a bug in ECS discovery in v1.x.x that might have caused this. We have completely rewritten the discovery process for v2.0.0 that was released today, previously we used AWS SDK calls to discover ECS resources but now we use AWS Config. I suspect this will fix that issue.
