### ISSUE TITLE
ElasticSearch Instance Types no longer supported

### ISSUE THREAD

**Issue by cruddasj** [awslabs/workload-discovery-on-aws#304]
**Describe the bug**
When deploying AWS perspective using the CloudFormation template at https://aws.amazon.com/solutions/implementations/aws-perspective, the allowed parameters for the ElasticSearch instance type are referencing what I believe to now be deprecated *.elasticsearch naming conventions. This causes the nested stack for the setup to fail and requires the CloudFormation template to be updated by users.:

https://github.com/awslabs/aws-perspective/blob/0b3d188d0d2ffdf1ed118c667aba6705c6206122/deployment/perspective-setup.yaml#L79.

**To Reproduce**

1. Go to 'https://aws.amazon.com/solutions/implementations/aws-perspective'
2. Click on 'Launch in the AWS Console'
3. Deploy the CloudFormation stack
4. See error in nested stack

**Expected behavior**
The CloudFormation template deploys all resources as expected.

**Screenshots**
N/A

**Browser (please complete the following information):**
N/A

**Additional context**
Whilst this issue was observed in the eu-west2 region, I believe this applies unilaterally across all regions given the naming convention change with the introduction of OpenSearch.

**Comment by svozza** [comment]
This has been addressed in v2.0.0 of Workload Discovery that was released today.
