### ISSUE TITLE
Automated deployment failed

### ISSUE THREAD

**Issue by GentaroKimura** [awslabs/workload-discovery-on-aws#321]
**Describe the bug**
CloudFormation stack creation fails

**To Reproduce**
1. Launth CloudFormation this [link](https://console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stacks/create/template?stackName=workload-discovery&templateURL=https://solutions-reference.s3.amazonaws.com/workload-discovery-on-aws/latest/workload-discovery-on-aws.template)
2. Specify stack details
3. See error

**Expected behavior**
receive a CREATE_COMPLETE status

**Screenshots**
![image](https://user-images.githubusercontent.com/103228531/202613589-9f1687ca-505c-41e9-a0d3-4877942e0f3a.png)

**Additional context**
tried in another region same result

**Comment by svozza** [comment]
We are working on a fix for this, there is a workaround described in #320. I will close this issue as it is a duplicate and we will track in #320.

**Comment by GentaroKimura** [comment]
@svozza Thanks for the fix. But I get the same error in v2.0.1.
![image](https://user-images.githubusercontent.com/103228531/203678479-3520a523-0365-4c86-a8de-88205a3c3f69.png)

**Comment by svozza** [comment]
That's a different error. It's regarding subnet groups only, not the parameter group. Go into the Neptune stack and there should be a more informative error message.

**Comment by GentaroKimura** [comment]
Thanks for the advice. I have identified the problem. 
I had set the Name tag to workload-discovery, so it was a Duplicate error.
I have succeeded when I left the Name tag blank.
![image](https://user-images.githubusercontent.com/103228531/203900489-64f29049-101e-4358-9711-f44843fdaa62.png)

**Comment by svozza** [comment]
Great news!
