### ISSUE TITLE
Taskstack -> CleanupECRRepository Failed to Complete

### ISSUE THREAD

**Issue by dieherna** [awslabs/workload-discovery-on-aws#322]
**Describe the bug**
Deployment of workload-discovery-on-aws.template CloudFormation template fails to complete. It fails under nested stack Taskstack on the Cleanup ECRRepository step (See attached image).

**To Reproduce**

To start off with, I was hitting issue 320 where the Neptune stack was failing to deploy. As per the workaround I deployed the template via the deploy local method

1. Cloned the "workload-discovery-on-aws" code
2. Modified the neptune.template file under the cfn folder as per the workaround provided issue 320
3. Carried out the steps exactly as documented. The local-deploy-script.sh file was updated with the details below:

AWS_REGION=us-east-1
DIST_OUTPUT_BUCKET=workload-discovery-on-aws
SOLUTION_NAME=workload-discovery-on-aws
VERSION=1.0.0
IMAGE_TAG=workload-discovery

4. After executing the script it generated the artifacts however it did not copy them to my S3 bucket. Unsure if this is also a bug
5. Manually uploaded the workload-discovery-on-aws.template located under the deployment/global-s3-assets folder to the root directory of my s3 bucket
6. Manually uploaded all files located under the deployment/regional-s3-assets folder to the "/workload-discovery-on-aws/1.0.0" directory of my s3 bucket
7. Deployed the "workload-discovery-on-aws.template" in my S3 bucket via CloudFormation 
8. Waited 30+ minutes before noticing the template failed to deploy

**Expected behavior**
The template should have completed to deploy successfully

**Screenshots**
Attached an image with the errors seen from the Taskstack nested stack

**Browser (please complete the following information):**

- Name: Safari
- Version 16.1

![Screen Shot 2022-11-23 at 9 52 55 AM](https://user-images.githubusercontent.com/24765431/203577596-2d994625-7c22-4151-a1d8-972a2a4b90e0.png)

**Comment by dieherna** [comment]
I just noticed the project was updated to v2.0.1 so decided to try deploying the regular (non local) CloudFormation template and it deployed as expected. Have not tried deployed local again since the v2.0.1 update.

**Comment by dieherna** [comment]
That's fair enough. I tried this on my laptop which is a Mac and I also tried it on an AWS EC2 instance running AWS linux and had the same problem. When running the deploy local script while in most instances it looked like it was ok I would see a lot of messages that looked like the one's below. Unsure if it could be related. Either way I now have the tool running on my AWS account after deploying v2.0.1 so everything looks good. I'll close the bug.

npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated @aws-sdk/util-base64-browser@3.188.0: The package @aws-sdk/util-base64-browser has been renamed to @aws-sdk/util-base64. Please install the renamed package.
npm WARN deprecated @aws-sdk/util-base64-node@3.188.0: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by svozza** [comment]
Do see any errors when the script outputs the following:

```
------------------------------------------------------------------------------
------------------------------------------------------------------------------
[Rebuild] Layers
------------------------------------------------------------------------------

# there will be a bunch of output here for building the layers, are there errors?

------------------------------------------------------------------------------
[Rebuild] Cleanup Bucket Lambda
------------------------------------------------------------------------------

```
